{"name": "test_update_existing_customer", "status": "broken", "statusDetails": {"message": "NameError: name 'random' is not defined. Did you forget to import 'random'?", "trace": "@pytest.fixture\n    def test_customer_data():\n        return {\n>           \"firstname\": generate_random_string(),\n            \"lastname\": generate_random_string(),\n            \"email\": generate_random_email(),\n            \"telephone\": generate_random_phone(),\n            \"password\": \"hashed_pass\",  # Подставляй заранее хэш, если нужно\n            \"newsletter\": 0,\n            \"status\": 1,\n        }\n\ntests/test_customer.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nlength = 6\n\n    def generate_random_string(length=6):\n>       return ''.join(random.choices(string.ascii_letters, k=length))\nE       NameError: name 'random' is not defined. Did you forget to import 'random'?\n\ntests/test_customer.py:12: NameError"}, "start": 1746280502678, "stop": 1746280502678, "uuid": "99488b93-ee90-4062-be29-39a2fba514fe", "historyId": "b2b1532b61fe997b7ba97520860addcb", "testCaseId": "b2b1532b61fe997b7ba97520860addcb", "fullName": "tests.test_customer#test_update_existing_customer", "labels": [{"name": "feature", "value": "Клиенты"}, {"name": "story", "value": "Обновление клиента"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "9957-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}