{"name": "test_update_existing_customer", "status": "broken", "statusDetails": {"message": "NameError: name 'test_customer_data_2' is not defined", "trace": "connection = <pymysql.connections.Connection object at 0x10b09dd30>\ntest_customer_data = {'email': 'initial@example.com', 'firstname': 'Initial', 'lastname': 'User', 'newsletter': 0, ...}\n\n    @allure.feature(\"Клиенты\")\n    @allure.story(\"Обновление клиента\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_update_existing_customer(connection, test_customer_data):\n        with allure.step(\"Создание клиента\"):\n>           customer_id = create_customer(connection, test_customer_data_2)\nE           NameError: name 'test_customer_data_2' is not defined\n\ntests/test_customer.py:54: NameError"}, "steps": [{"name": "Создание клиента", "status": "broken", "statusDetails": {"message": "NameError: name 'test_customer_data_2' is not defined\n", "trace": "  File \"/Users/aleks/QA-hw/opencart_db_framework/tests/test_customer.py\", line 54, in test_update_existing_customer\n    customer_id = create_customer(connection, test_customer_data_2)\n                                              ^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1746280121389, "stop": 1746280121389}], "start": 1746280121389, "stop": 1746280121392, "uuid": "9463fea1-9fac-4e4f-a06f-9f2e3a45939a", "historyId": "b2b1532b61fe997b7ba97520860addcb", "testCaseId": "b2b1532b61fe997b7ba97520860addcb", "fullName": "tests.test_customer#test_update_existing_customer", "labels": [{"name": "story", "value": "Обновление клиента"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Клиенты"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "8836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}